# Generated by Django 5.0.2 on 2024-02-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_and_folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
