# Generated by Django 5.0.2 on 2024-02-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_and_folders', '0002_rename_created_at_file_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parentFolderId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_and_folders.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parentFolderId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_and_folders.folder'),
        ),
    ]
